apiVersion: v1
kind: Secret
metadata:
  name: rest-proxy-secrets
  namespace: operator
type: Opaque
stringData:
    KAFKA_REST_SSL_KEYSTORE_PASSWORD: "confluent"
    KAFKA_REST_SSL_KEY_PASSWORD: "confluent"
    KAFKA_REST_SSL_TRUSTSTORE_PASSWORD: "mystorepassword"
    KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD: "confluent"
    KAFKA_REST_CLIENT_SSL_KEY_PASSWORD: "confluent"
    KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD: "mystorepassword"
    KAFKA_REST_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: "mystorepassword"
    KAFKA_REST_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEYSTORE_PASSWORD: "confluent"
    KAFKA_REST_CONFLUENT_MONITORING_INTERCEPTOR_SSL_KEY_PASSWORD: "confluent"
    KAFKA_REST_CONFLUENT_MONITORING_INTERCEPTOR_SSL_TRUSTSTORE_PASSWORD: "mystorepassword"
    KAFKA_REST_CONFLUENT_METADATA_BASIC_AUTH_USER_INFO: "user1:kafka-secret"
    KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required username=\"user1\" password=\"kafka-secret\"  metadataServerUrls=\"http://kafka.operator.svc.cluster.local:8091\";"
