apiVersion: v1
kind: Service
metadata:
  name: rest-proxy-0-internal
  namespace: operator
  labels:
    app: rest-proxy
spec:
  ports:
  - port: 8082
    name: extenal
    protocol: TCP
    targetPort: 8082
  selector:
    app: rest-proxy
